[workspace]
members = [
  "crates/simtest-funnel-core",
  "crates/simtest-funnel-python",
  "crates/simtest-funnel-wasm",
]
resolver = "2"

[workspace.package]
version = "1.0.0-beta.4"
edition = "2021"
license = "MIT"
authors = ["Symoptia contributors"]
repository = "https://github.com/Symoptia/simtest-funnel.git"
