[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "simtest-funnel"
version = "1.0.0-beta.1"
description = "Trajectory comparison library"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT" }
authors = [{ name = "Symoptia contributors" }]

[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "simtest.funnel._simtest_funnel"
python-source = "python"
python-packages = ["simtest"]
requires-python = ">=3.12"
